name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 3'  # Às 6 da manhã todas as quartas-feiras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository using the latest version
      - name: Checkout repository
        uses: actions/checkout@v3

      # Custom Shell Script
      - name: Run custom shell script
        run: |
          echo "Olá! Este é um script personalizado em Shell."
          echo "A data e hora atuais são: $(date)"

      # Setup Node.js environment using the latest version
      - name: Setup Node.js environment
        uses: actions/setup-node@v3  # Certifique-se de usar a versão 3
        with:
          node-version: '20'

      # Custom Node.js Script
      - name: Run custom Node.js script
        run: |
          echo "console.log('Olá! Este é um script personalizado em Node.js.');" > meu_script_temp.js
          echo "console.log('A data e hora atuais são:', new Date().toLocaleString());" >> meu_script_temp.js
          node meu_script_temp.js
